### PR TITLE
make type formatters configurable

### PR DESCRIPTION
**Pull request by Rauno56**
Need for a custom formatters is real. #27 also shows that. Implemented solution as simple as possible for now.

### CODE REVIEW

**Comment by wdavidw** [comment]
looks good, thanks

**Comment by MichielDeMey** [comment]
Would be nice if there was an example on how to use this.
Although it's self-explanatory I had to search the issues to find this. :)

**Comment by wdavidw** [comment]
please provide with the sample that make the most sense to you (and that would have help you the most) and i'll integrate it to the website

**Comment by Rauno56** [comment]
... or even better: Create another PR and get into the hall of fame, @MichielDeMey!

**Comment by wdavidw** [comment]
yes, website is [here](https://github.com/wdavidw/node-csv-docs)

**Comment by MichielDeMey** [comment]
I've used a custom formatter for my dates. Data is piped directly from MongoDB and time gets converted to unix timestamps by default.

Here's a snippet of my formatter (using moment.js):
```js
const stringifier = stringify({
  formatters: {
    date: (value) => moment(value).format('YYYY-MM-DD')
  }
});

generator.pipe(stringifier).pipe(process.stdout);
```

I'll send out a PR for the website soon.

**Comment by wdavidw** [comment]
great, closing then, waiting for the PR

**Pull request merged**
