### PR TITLE
allow columns to be nested

### LINKED ISSUE #23: Using nested columns
I ran into the follow issue:

1. I have a data Model (Mongoose) in this case.
2. My Model has some nested properties.
3. Csv stringify columns do not seems to be able to find properties deeper than level 1. 
4. I would like to be able to access my nested models and map then to csv columns without the need to first mapping them to level 1 properties on the same model.

```
// Example Model
var model = {
  'nameOnModel' : 'myName',
  'address': {
    'street' : 'LongRoad'
  }
}

var columns = {
  'nameOnModel' : 'nameOfHeader', // This works fine
  'address.street' : 'street' // This does not
}
var stringifier = csv.stringify({columns: columns, header: true})

stringifier.write(model)
stringifier.pipe(process.stdout)

// Output
nameOfHeader, street
myName, 
```

### PR DESCRIPTION
**Pull request by robinjoseph08**
Fixes #23 

The best way I thought to achieve this functionality was through [lodash's get function](https://lodash.com/docs#get). That does mean it adds it as a dependency, but since lodash splits up all of it's functions into individual npm packages, the dependency is actually quite small. If this isn't acceptable, I'll try to find another way to accomplish this.

### CODE REVIEW

**Comment by robinjoseph08** [comment]
@wdavidw can you check out this PR? Thanks!

**Comment by wdavidw** [comment]
i'll rather copy/paste the lodash.get function into the code, if the lodash license permit it (and with acknowledgement in the comment). would also be nice to update the [documentation](https://github.com/wdavidw/node-csv-docs/tree/master/src/documents/parse). otherwise, great contribution.

**Comment by robinjoseph08** [comment]
@wdavidw I can copy it in, but it's about 80 lines of JavaScript (as opposed to CoffeeScript). Is this the preferred method instead of just requiring it from npm?

And I'll definitely add documentation :+1:

**Comment by wdavidw** [comment]
copying 80 lines versus including a dependency, I'm really hesitating, do what seems the best to you.

**Comment by robinjoseph08** [comment]
@wdavidw Thanks for giving me the choice. I think it's better to include the dependency instead for a few reasons:

* If there are any updates that are made to the lodash get function, you can now easily upgrade the module to get them.
* The code in your project remains centric to what it's meant to do: stringify JSON into CSV format.
* Your code stays consistent by only having content written in CoffeeScript.
* If you bring this code into your repo, you'd also have to bring in the tests for it, which is unnecessary since it's _technically_ already tested, but is necessary just in case anything breaks.
* With the newer versions of `npm` if there are any packages shared by a user's dependencies, it pulls them out to avoid duplication. This won't be possible if it's not a separate package.
* This is what `npm` dependencies are made for.

I'll get started on the PR to update the documentation now. If there was anything else you wanted me to do in this PR, let me know!

**Comment by wdavidw** [comment]
great, thanks

**Comment by robinjoseph08** [comment]
Thanks for merging! Any possibility of releasing a new version on npm?

**Pull request merged**
